"""Init database tables

Revision ID: 040cc5bbd07f
Revises: 5e7a7e7cc37d
Create Date: 2026-09-22 21:25:25.046394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040cc5bbd07f'
down_revision: Union[str, None] = '5e7a7e7cc37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
